In [13]:
print('Welcome to NumPy')

Welcome to NumPy


In [14]:
import numpy as np
import time
import sys

## Why NumPy over List

### Small sized

In [38]:
list1 = range(100000)
print(sys.getsizeof(list1[0])*100000)

ar1 = np.arange(100000)
print(ar1.size*ar1.itemsize)

2400000
400000


### Faster

In [45]:
list1 = range(100000)
list2 = range(100000)

time1 = time.time()
list2 = [a+b for a, b in zip(list1, list2)]

print((time.time()-time1)*10000)

ar1 = np.arange(100000)
ar2 = np.arange(100000)

time2 = time.time()
ar2 = ar1+ar2
print((time.time()-time2)*100000)

228.7006378173828
8670.759201049805


### Easy Computations

In [50]:
list1 = [1,2,3,4,5]
list2 = [5,4,3,2,1]
summ = [i+j for i, j in zip(list1,list2)]
print(summ)

ar1 = np.array([1,2,3,4,5])
ar2 = np.array([5,4,3,2,1])
summ = ar1+ar2
print(summ)

[6, 6, 6, 6, 6]
[6 6 6 6 6]


### N Dimentional Array

In [104]:
ar1d = np.array([1,2,3,4,5], dtype='int64')
print(ar1d)
print(ar1d.ndim)
print(ar1d.shape)
print(ar1d.dtype)
print(ar1d.size*ar1d.itemsize)
print(ar1d.nbytes)

[1 2 3 4 5]
1
(5,)
int64
40
40


In [106]:
ar2d = np.array([[1,2,3,4,5],[2,4,6,8,0]])
print(ar2d)
print(ar2d.ndim)
print(ar2d.shape)
print(ar2d.dtype)
print(ar2d.size*ar2d.itemsize)
print(ar2d.nbytes)

[[1 2 3 4 5]
 [2 4 6 8 0]]
2
(2, 5)
int32
40
40


In [107]:
ar3d = np.array([[[1,2,3,4,5],[2,4,6,8,0]],[[1,2,3,4,5],[1,3,5,7,9]]])
print(ar3d) 
print(ar3d.ndim)
print(ar3d.shape)
print(ar3d.dtype)
print(ar3d.size*ar3d.itemsize)
print(ar3d.nbytes)

[[[1 2 3 4 5]
  [2 4 6 8 0]]

 [[1 2 3 4 5]
  [1 3 5 7 9]]]
3
(2, 2, 5)
int32
80
80


In [108]:
ar4d = np.array([[[[1],[1]],[[1],[1]], [[1],[1]],[[1],[1]]], [[[1],[1]],[[1],[1]], [[1],[1]],[[1],[1]]]])
print(ar4d)
print(ar4d.ndim)
print(ar4d.shape)
print(ar4d.dtype)
print(ar4d.size*ar4d.itemsize)
print(ar4d.nbytes)

[[[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]]
4
(2, 4, 2, 1)
int32
64
64


## Slicing, Indexing and Reshaping

In [133]:
slicing = np.array([[['a','b','c'],['a', 'b', 'c']],[['c', 'b', 'a'],['b','c','a']]])
print(slicing)
print(slicing[1,1,1])               # element at1th row's 1th col of 1th slice of 3d array
print('Slice at [0:,0:,1]  :\n ',slicing[0:,0:,1],'\n')
slicing[0:,0:,1]=[[1,1],[2,2]]      #assigning new values    
print('After assignment   :\n',slicing)
print('Reshaped  : \n',slicing.reshape(3,2,2))

[[['a' 'b' 'c']
  ['a' 'b' 'c']]

 [['c' 'b' 'a']
  ['b' 'c' 'a']]]
c
Slice at [0:,0:,1]  :
  [['b' 'b']
 ['b' 'c']] 

After assignment   :
 [[['a' '1' 'c']
  ['a' '1' 'c']]

 [['c' '2' 'a']
  ['b' '2' 'a']]]
Reshaped  : 
 [[['a' '1']
  ['c' 'a']]

 [['1' 'c']
  ['c' '2']]

 [['a' 'b']
  ['2' 'a']]]


## Initialising an array

In [136]:
np.zeros((5,5))                                      # array with all zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [138]:
np.ones((5,5))                                      # 5X5 array with all ones  

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [156]:
arr = np.full((5,5), 5)                                  # 5X5 with all 5
print(arr)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [157]:
np.full_like(arr,15)                                    # array like arr 

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [160]:
np.random.rand(2,2,5)                                 # gives array of given size values 0-1

array([[[0.1837441 , 0.29326603, 0.26013539, 0.18134089, 0.55064107],
        [0.06449073, 0.93759379, 0.54198664, 0.97197053, 0.14721361]],

       [[0.03907645, 0.93171   , 0.82747529, 0.72811746, 0.4358824 ],
        [0.27756008, 0.97420049, 0.35194944, 0.058216  , 0.98830639]]])

In [163]:
np.random.random_sample(arr.shape)                   

array([[0.61995649, 0.16792972, 0.09076765, 0.53765607, 0.93442098],
       [0.24304683, 0.44950302, 0.93016929, 0.37370564, 0.90715145],
       [0.63182651, 0.14392902, 0.49196004, 0.61878507, 0.06894629],
       [0.91467261, 0.8949256 , 0.10662388, 0.63023388, 0.42840266],
       [0.11441561, 0.8085523 , 0.26540261, 0.66912789, 0.16458094]])

In [171]:
np.random.randint(2,5, size=(5,5))                   # array with random integers of given size

array([[4, 2, 3, 4, 3],
       [4, 2, 4, 2, 4],
       [3, 3, 2, 3, 3],
       [2, 3, 2, 3, 2],
       [2, 2, 4, 2, 4]])

In [176]:
a = np.identity(3)                                      # identity matrix of size 3
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [189]:
np.repeat([a[0,:]],3, axis=1)

array([[1., 1., 1., 0., 0., 0., 0., 0., 0.]])

In [190]:
np.repeat([a[0,:]],3, axis=0)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [192]:
import ipkernel
help('modules')

ModuleNotFoundError: No module named 'ipkernel'

In [194]:
np.sqrt(16)

4.0

In [207]:
b = np.ones((5,5))
b[1:4,1:4]=0
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
