In [13]:
print('Welcome to NumPy')

Welcome to NumPy


In [14]:
import numpy as np
import time
import sys

## Why NumPy over List

### Small sized

In [38]:
list1 = range(100000)
print(sys.getsizeof(list1[0])*100000)

ar1 = np.arange(100000)
print(ar1.size*ar1.itemsize)

2400000
400000


### Faster

In [45]:
list1 = range(100000)
list2 = range(100000)

time1 = time.time()
list2 = [a+b for a, b in zip(list1, list2)]

print((time.time()-time1)*10000)

ar1 = np.arange(100000)
ar2 = np.arange(100000)

time2 = time.time()
ar2 = ar1+ar2
print((time.time()-time2)*100000)

228.7006378173828
8670.759201049805


### Easy Computations

In [50]:
list1 = [1,2,3,4,5]
list2 = [5,4,3,2,1]
summ = [i+j for i, j in zip(list1,list2)]
print(summ)

ar1 = np.array([1,2,3,4,5])
ar2 = np.array([5,4,3,2,1])
summ = ar1+ar2
print(summ)

[6, 6, 6, 6, 6]
[6 6 6 6 6]


### N Dimentional Array

In [104]:
ar1d = np.array([1,2,3,4,5], dtype='int64')
print(ar1d)
print(ar1d.ndim)
print(ar1d.shape)
print(ar1d.dtype)
print(ar1d.size*ar1d.itemsize)
print(ar1d.nbytes)

[1 2 3 4 5]
1
(5,)
int64
40
40


In [99]:
ar2d = np.array([[1,2,3,4,5],[2,4,6,8,0]])
print(ar2d)
print(ar2d.ndim)
print(ar2d.shape)
print(ar2d.dtype)
print(ar2d.size*ar2d.itemsize)

[[1 2 3 4 5]
 [2 4 6 8 0]]
2
(2, 5)
int32
40


In [98]:
ar3d = np.array([[[1,2,3,4,5],[2,4,6,8,0]],[[1,2,3,4,5],[1,3,5,7,9]]])
print(ar3d) 
print(ar3d.ndim)
print(ar3d.shape)
print(ar3d.dtype)
print(ar3d.size*ar3d.itemsize)

[[[1 2 3 4 5]
  [2 4 6 8 0]]

 [[1 2 3 4 5]
  [1 3 5 7 9]]]
3
(2, 2, 5)
int32
80


In [97]:
ar4d = np.array([[[[1],[1]],[[1],[1]], [[1],[1]],[[1],[1]]], [[[1],[1]],[[1],[1]], [[1],[1]],[[1],[1]]]])
print(ar4d)
print(ar4d.ndim)
print(ar4d.shape)
print(ar4d.dtype)
print(ar4d.size*ar4d.itemsize)

[[[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]


 [[[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]

  [[1]
   [1]]]]
4
(2, 4, 2, 1)
int32
64
